/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gvillena;

/**
 *
 * @author alumno
 */
public class MainForm1 extends javax.swing.JFrame {

    /**
     * Creates new form MainForm1
     */
    public MainForm1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plTiposTarjeta = new javax.swing.JPanel();
        lbltipostarjeta = new javax.swing.JLabel();
        lbltipostarjetaimag = new javax.swing.JLabel();
        lblpago = new javax.swing.JLabel();
        pldatos = new javax.swing.JPanel();
        lblnombre = new javax.swing.JLabel();
        lblnumtarjeta = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        lblnom = new javax.swing.JTextField();
        lblnumtarje = new javax.swing.JTextField();
        lblcodi = new javax.swing.JTextField();
        lblfecha = new javax.swing.JLabel();
        lbldia = new javax.swing.JSpinner();
        lblmes = new javax.swing.JSpinner();
        lblimatarjeta = new javax.swing.JLabel();
        btnmetodo = new javax.swing.JButton();
        bntcomparr = new javax.swing.JButton();
        bntatras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltipostarjeta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbltipostarjeta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltipostarjeta.setText("Aceptamos:");
        lbltipostarjeta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lbltipostarjetaimag.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltipostarjetaimag.setIcon(new javax.swing.ImageIcon("D:\\brayan\\4ciclo\\lpoo\\tarjeta.jpg")); // NOI18N
        lbltipostarjetaimag.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout plTiposTarjetaLayout = new javax.swing.GroupLayout(plTiposTarjeta);
        plTiposTarjeta.setLayout(plTiposTarjetaLayout);
        plTiposTarjetaLayout.setHorizontalGroup(
            plTiposTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plTiposTarjetaLayout.createSequentialGroup()
                .addGroup(plTiposTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plTiposTarjetaLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lbltipostarjeta))
                    .addComponent(lbltipostarjetaimag))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plTiposTarjetaLayout.setVerticalGroup(
            plTiposTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plTiposTarjetaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbltipostarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltipostarjetaimag)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblpago.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblpago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpago.setText("Pago con Tarjeta");

        lblnombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnombre.setText("Nombre del Titular ");

        lblnumtarjeta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnumtarjeta.setText("Numero de la tarjeta");

        lblcodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblcodigo.setText("CVV(codigo de seguridad");

        lblnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblnomActionPerformed(evt);
            }
        });

        lblfecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblfecha.setText("Fecha de Caducidad de la Tarjeta");

        javax.swing.GroupLayout pldatosLayout = new javax.swing.GroupLayout(pldatos);
        pldatos.setLayout(pldatosLayout);
        pldatosLayout.setHorizontalGroup(
            pldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pldatosLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pldatosLayout.createSequentialGroup()
                        .addComponent(lblfecha)
                        .addGap(18, 18, 18)
                        .addComponent(lbldia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblmes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pldatosLayout.createSequentialGroup()
                        .addGroup(pldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnumtarjeta)
                            .addComponent(lblnombre)
                            .addComponent(lblcodigo))
                        .addGap(73, 73, 73)
                        .addGroup(pldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblnumtarje, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addComponent(lblnom))
                            .addComponent(lblcodi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pldatosLayout.setVerticalGroup(
            pldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pldatosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre)
                    .addComponent(lblnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnumtarjeta)
                    .addComponent(lblnumtarje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodigo)
                    .addComponent(lblcodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfecha)
                    .addComponent(lbldia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        lblimatarjeta.setIcon(new javax.swing.ImageIcon("D:\\brayan\\4ciclo\\lpoo\\visa.PNG")); // NOI18N

        btnmetodo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnmetodo.setText("OTRO METODO DE PAGO");
        btnmetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmetodoActionPerformed(evt);
            }
        });

        bntcomparr.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bntcomparr.setText("CONFIRMAR COMPRA");

        bntatras.setText("atras");
        bntatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntatrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(plTiposTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lblpago, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pldatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(bntatras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnmetodo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntcomparr)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(lblimatarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblpago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plTiposTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pldatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnmetodo)
                            .addComponent(bntcomparr)
                            .addComponent(bntatras))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblimatarjeta)
                        .addGap(140, 140, 140))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblnomActionPerformed

    private void btnmetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmetodoActionPerformed

    private void bntatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntatrasActionPerformed
        // TODO add your handling code here:
         MainForm b = new MainForm();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntatrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntatras;
    private javax.swing.JButton bntcomparr;
    private javax.swing.JButton btnmetodo;
    private javax.swing.JTextField lblcodi;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JSpinner lbldia;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblimatarjeta;
    private javax.swing.JSpinner lblmes;
    private javax.swing.JTextField lblnom;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JTextField lblnumtarje;
    private javax.swing.JLabel lblnumtarjeta;
    private javax.swing.JLabel lblpago;
    private javax.swing.JLabel lbltipostarjeta;
    private javax.swing.JLabel lbltipostarjetaimag;
    private javax.swing.JPanel plTiposTarjeta;
    private javax.swing.JPanel pldatos;
    // End of variables declaration//GEN-END:variables
}
